on:
  push:
    tags:
      - '*'
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
    - name : checkout
      uses: actions/checkout@v3.3.0

#    - name : Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#       java-version: '17'
#       distribution: 'temurin'
#
#    - name: Set up android SDK
#      uses: android-actions/setup-android@v3
    
    - name : export game
      uses: firebelley/godot-export@v5.2.0
      id: export      
      with:
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-beta1/Godot_v4.3-beta1_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-beta1/Godot_v4.3-beta1_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        cache: true

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.EXPORT_GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
